[package]
name = "baremetal"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = { version = "0.7.7", features = ["cm7", "critical-section-single-core", "inline-asm"] }
cortex-m-rt = "0.7.0"
panic-halt = "0.2.0"
